services: 
  mariadb: 
    image: 'bitnami/mariadb:latest' 
    environment:
     - ALLOW_EMPTY_PASSWORD=yes
     - MARIADB_USER=bn_myapp
     - MARIADB_DATABASE=bitnami_myapp
     - MARIADB_PASSWORD=b1tnam1_my@pp 
    volumes:
      - 'mariadb_data:/bitnami/mariadb' 
    networks:
      - laravel-network 
  application: 
    image: 'bitnamilegacy/laravel:latest' 
    environment:
      - LARAVEL_DATABASE_TYPE=mysql
      - LARAVEL_DATABASE_HOST=mariadb
      - LARAVEL_DATABASE_PORT_NUMBER=3306
      - LARAVEL_DATABASE_NAME=bitnami_myapp
      - LARAVEL_DATABASE_USER=bn_myapp
      - LARAVEL_DATABASE_PASSWORD=b1tnam1_my@pp 
    ports:
     - '8000:8000' 
    volumes:
      - './src:/app' 
    depends_on:
       - mariadb 
    networks:
      - laravel-network 

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HTTP_PORT: 8080
    ports:
     - "0.0.0.0:8080:8080"
    depends_on:
     - postgres
    networks:
     - laravel-network
    command: start-dev

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
     - laravel-network
    volumes:
     - postgres_data:/var/lib/postgresql/data


volumes: 
  mariadb_data: 
    driver: local 
  postgres_data:
    driver: local
  
networks: 
  laravel-network: 
    driver: bridge